name: Checkstyle CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
      - uses: reviewdog/action-setup@v1
          with:
            reviewdog_version: latest
      - name: Checkstyle with Gradle
        run: ./gradlew check
      - name: Upload Report
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: test results
          path: build/reports/checkstyle
      - name: Run reviewdog
          env:
            REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            reviewdog -reporter=github-pr-check -runners=golint,govet
            # or
            reviewdog -reporter=github-pr-review -runners=golint,govet
